services:
  gas:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: ${CONTAINER_NAME:-gas}
    volumes:
      - ../:/usr/app
      - gas-node-modules:/usr/app/node_modules
    working_dir: /usr/app
    tty: true

volumes:
  gas-node-modules: